# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02d37f4a92f07144424f588b122bc21e5dcf9e500d73c73cce7b843063269ab7a261288ac85518aae37313a9aa04c63450406863aaf4f61c3a1ed2be8972d078

test:
  secret_key_base: 5babd29a76c5afa8acc1dcdab974c96dd24e21f2f7dddd2d76719ce21c4eae53e3cd60124701662bd8915d5a8d0b8b820620e44f3f537b2efb6123fd3e1de502

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
